### ISSUE TITLE
AngularAOP for advising controller 

### ISSUE THREAD

**Issue by ptgamr** [mgechev/angular-aop#17]
Hi there, 
Currently, I see that AngularAOP on has the support for advising Angular's service. However, it might be useful if it can support advising controllers as well, because you can have Authorization, Exception handling in controllers, not only in services.

Would be very nice to have that,
Cheers

**Comment by cenoicc** [comment]
I've been demoing the use of this library for a project I'm working on, and I can definitely see the benefits of aop in this context.  I agree that having support for advising Angular controllers would be a fantastic addition.  Thank you so much for the work you've put into this.

**Comment by mgechev** [comment]
In order to allow declarative style of definition of the pointcuts (i.e. as configuration object passed to the `executeProvider`) patching of `$controller` will be required. I'm really not such a big fan of this idea. Same thing is holding me for implementing ["More flexible way of defining pointcuts"](https://github.com/mgechev/angular-aop#roadmap).
